name: Kubernetes E2E Testing

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  minikube-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          java-package: jdk
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: |
          mvn -B -Dmaven.test.skip=true -T 2C clean package dockerfile:build
          docker tag kubernetes-springboot-demo:0.0.2 registry.cn-shanghai.aliyuncs.com/dockerhub2019/spring:0.0.2
          docker images
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.6.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.3'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the single node cluster
        run: |
          kubectl version
          sleep 15
          kubectl get nodes
          ls -lh|grep -i yaml
          kubectl apply -f redis-deployment.yaml
          kubectl apply -f redis-service.yaml
          kubectl apply -f spring-config.yaml
          kubectl apply -f spring-deployment.yaml
          kubectl apply -f spring-service.yaml
          kubectl get po
          sleep 30
          kubectl get po
          curl -vsSL localhost:30080/hello
          curl -sSL localhost:30080/redis
          curl -sSL localhost:30080/config
